### ISSUE TITLE
Generating Random Hyperbolic Graphs

### ISSUE THREAD

**Issue by yen-hsiang-chang** [VieCut/VieCut#9]
Hi All,
     I am trying to generate random hyperbolic graphs used in the benchmarks of the first two papers, by using NetworKit and following the parameters specified in the appendix, i.e., power law of exponent 5, number of vertices and average degrees. However, no matter how I change the configurations of number of vertices and average degrees, none of the graphs have non-trivial minimum cuts, i.e., all of them have a minimum degree equal to the minimum cut. Do you specify other parameters, or do you have any script that can generate random hyperbolic graphs without trivial minimum cut?
     
Thanks,
Yen-Hsiang

**Comment by schulzchristian** [comment]
@alexnoe can you help?

**Comment by alexnoe** [comment]
Sorry for the late response, Christian, we had solved this offline via mail. Closing this ticket.

Feel free to re-open this if you have any further issue or question, Yen-Hsiang.
